### ISSUE TITLE
New Resonite Update Moves `Record` to FrooxEngine.Store.dll 

### ISSUE THREAD

**Issue by stiefeljackal** [art0007i/CustomInspectors#2]
With the new Resonite update (2023.11.24.1379 and above), the `Record` class has been moved to `FrooxEngine.Store.dll` which needs to be referenced now. Pull Request #1 fixes this issue.

**Comment by art0007i** [comment]
fixed in https://github.com/art0007i/CustomInspectors/releases/tag/2.1.1
